# Basic Neural Network in Numpy

In [1]:
import numpy as np
np.random.seed(1)

In [2]:
X = np.random.randint(0, 2, size=(10, 6))
y = np.random.randint(0, 2, size=(10, 1))

In [3]:
W1 = 2 * np.random.random((6, 3)) - 1
W2 = 2 * np.random.random((3, 1)) - 1

In [4]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def nll(target, pred):
    return np.sum(-target * np.log(pred))

In [5]:
N = 10000
for i in range(N):
    h = sigmoid(np.dot(X, W1))  # (100, 3)
    out = sigmoid(np.dot(h, W2))  # (100, 1)
    dout = (y - out) * (out * (1 - out))  # (100, 1)
    dh = np.dot(dout, W2.T) * (h * (1 - h))  # (100, 3)
    W2 = W2 + np.dot(h.T, dout)
    W1 = W1 + np.dot(X.T, dh)

print("W1:", W1)
print("W2:", W2)

y_hat = sigmoid(np.dot(sigmoid(np.dot(X, W1)), W2))
print("Logloss", np.round(nll(y, y_hat), 3))

W1: [[-0.41128669  1.0079097  -0.53547132]
 [-1.44689343 -6.61011106  6.22347221]
 [-0.40247243  4.14121639 -3.88479384]
 [ 2.05204952 -1.55322022  1.00024174]
 [-2.52201087  0.06071088 -0.46524165]
 [-2.70200844  4.13693156 -3.86986874]]
W2: [[-3.89629064]
 [ 9.80818315]
 [-8.75867543]]
Logloss 0.017
